// <auto-generated />
namespace FilmFriends.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FilmFriendsDataFilmFriendsContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FilmFriendsDataFilmFriendsContext));
        
        string IMigrationMetadata.Id
        {
            get { return "202409262226410_FilmFriends.Data.FilmFriendsContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
